name: Database Setup on Self-hosted Runner - Local

on:
  push:
    branches:
      - ubuntulocal-createDatabase  # Run only when pushing to main

jobs:
  setup-database:
    runs-on: ubuntulocal  # Use your self-hosted runner

    steps:
      - name: Install MySQL (if not installed)
        run: |
          echo "${{ secrets.SUDO_PASSWORD_Local }}" | sudo -S apt-get update          
          echo "${{ secrets.SUDO_PASSWORD_Local }}" | sudo -S apt-get install -y mysql-server
  
      - name: Drop Database if it exists
        run: |
          echo "${{ secrets.SUDO_PASSWORD_Local }}" | sudo -S mysql -h ${{ secrets.DB_HOST }} -u root -p${{ secrets.MYSQL_ROOT_PASSWORD }} -e "
          DROP DATABASE IF EXISTS ${{ secrets.DB_DATABASE }};"
      
      - name: Create Database
        run: |
          echo "${{ secrets.SUDO_PASSWORD_Local }}" | sudo -S mysql -h ${{ secrets.DB_HOST }} -u root -p${{ secrets.MYSQL_ROOT_PASSWORD }} -e "
          CREATE DATABASE ${{ secrets.DB_DATABASE }};"
    
      - name: Set root password for MySQL
        run: |
            echo "${{ secrets.SUDO_PASSWORD_Local }}" | sudo -S mysql -h ${{ secrets.DB_HOST }} -u root -p${{ secrets.MYSQL_ROOT_PASSWORD }} -e "
            ALTER USER 'root'@'${{ secrets.DB_HOST }}' IDENTIFIED WITH mysql_native_password BY '${{ secrets.MYSQL_ROOT_PASSWORD }}';"
            echo "${{ secrets.SUDO_PASSWORD_Local }}" | sudo -S mysql -h ${{ secrets.DB_HOST }} -u root -p${{ secrets.MYSQL_ROOT_PASSWORD }} -e "FLUSH PRIVILEGES;"
  
      - name: Create Database User and Grant Privileges
        run: | # SUDO_PASSWORD_Local is the password for the local machine sudo command.
          echo "${{ secrets.SUDO_PASSWORD_Local }}" | sudo -S mysql -h ${{ secrets.DB_HOST }} -u root -p${{ secrets.MYSQL_ROOT_PASSWORD }} -e "
          CREATE USER IF NOT EXISTS '${{ secrets.DB_USERNAME }}'@'%' IDENTIFIED BY '${{ secrets.DB_PASSWORD }}';
          GRANT ALL PRIVILEGES ON ${{ secrets.DB_DATABASE }}.* TO '${{ secrets.DB_USERNAME }}'@'%';
          FLUSH PRIVILEGES;"
